module.exports = {
    // BASE_URL: 'http://192.168.0.79:9009/api/v1/',  
    BASE_URL: 'http://www.api.ugigs.co.uk/' ,
    IMAGE_BASE_URL: 'http://www.ugigs.co.uk/',



    //artist
    ARTISTREGISTER: 'projects/register.php',
    LOGIN: 'projects/login.php',    
    GETPROJECTLIST: 'projects/getProjectList.php',
    GETPENDINGGIGS: 'projects/getPendingGigs.php',
    GETPROJECT: 'projects/getProject.php',
    GETUPCOMINGGIGS: 'projects/getUpcomingGigs.php',
    GETPREVIOUSGIGS: 'projects/getPreviousGigs.php',
    SEARCHBYNAME: 'projects/searchByName.php',
    ADDUNAVAILABLEDATE: 'projects/addUnavailableDate.php',
    DELETEUNAVAILABLEDATE: 'projects/deleteUnavailableDate.php',
    GETUNAVAILABLEDATELIST: 'projects/getUnavailableDateList.php',
    GETPROJECTWITHRATEREVIEW: 'projects/getProjectWithRateReview.php',
    CHANGEPASSWORD: 'projects/changePassword.php',
    ARTISTDELETEACCOUNT: 'projects/deleteAccount.php',
    GETMESSAGELIST: 'projects/getMessageList.php',
    DELETEMESSAGE: 'projects/DeleteMessage.php',
    SEARCHPROJECT: 'projects/searchProject.php',   
    GIVERATEREVIEW: 'projects/giveRateReview.php',
    ARTISTACCEPTGIG: 'projects/acceptGigs.php',
    ARTISTREJECTGIG: 'projects/rejectGigs.php',
    ARTISTFORGOTPASSWORD: 'projects/forgotPassword.php',
    ARTISTCHANGEEMAIL: 'projects/changeEmailAddress.php',
    SENDMESSAGE: 'projects/sendMessage.php',
    PUTLOOKINGFOR: 'venues/putLookingFor.php',
    ARTISTEDITPROFILE: 'projects/editProjectProfile.php',
    ARTISTREGION: 'projects/getRegionList.php',
    TYPEOFARTIST: 'projects/getProjectTypes.php',
    ADDUNAVAILABELDATE: 'projects/addUnavailableDate.php',
    GETUNAVAILABELDATE: 'projects/getUnavailableDateList.php',
    DELETEUNAVAILABLEDATE: 'projects/deleteUnavailableDate.php',
    GETLASTMINGIGLIST: 'projects/getLastMinuteGigsList.php',
    GETLASTMINGIGLISTBYTYPE: 'projects/getLastMinuteGigsListByType.php',


    //venue
    VENUEREGISTER: 'venues/register.php',    
    VENUELOGIN: 'venues/login.php',
    GETVENUELIST: 'venues/getVenueList.php',
    GETVENUE: 'venues/getVenue.php',
    GETVENUEPENDINGINVITES: 'venues/getPendingInvites.php',
    GETVENUEUPCOMINGGIGS: 'venues/getUpcomingGigs.php',
    GETVENUEPREVIOUSGIGS: 'venues/getPreviousGigs.php',
    VENUESEARCHBYNAME: 'venues/searchByName.php',
    // GETVENUEWITHRATEREVIEW: 'venues/getVenueWithRateReview.php', 
    VENUEDELETEUNAVAILABLEDATE: 'venues/deleteUnavailableDate.php', 
    VENUEGETUNAVAILABLEDATELIST: 'venues/getUnavailableDateList.php', 
    VENUECHANGEPASSWORD: 'venues/changePassword.php', 
    VENUEDELETEACCOUNT: 'venues/deleteAccount.php', 
    VENUEGETMESSAGELIST: 'venues/getMessageList.php', 
    VENUEDELETEMESSAGE: 'venues/deleteMessage.php', 
    CONTACTUS: 'venues/contactUs.php',
    // ACCEPTGIGS: 'venues/AcceptGigs.php',
    // REJECTGIGS: 'venues/RejectGigs.php',
    GETRATEREVIEW: 'venues/getVenueWithRateReview.php', 
    VENUESEARCHPROJECT: 'venues/SearchProject.php',
    CHANGEEMAILADDRESS: 'venues/changeEmailAddress.php', 
    VENUEGETLOOKINGFOR: 'venues/getLookingFor.php',
    VENUEPUTLOOKINGFOR: 'venues/putLookingFor.php',
    SEARCHVENUE: 'venues/searchVenue.php',
    VENUEACCEPTGIGS: 'venues/acceptGigs.php',
    VENUEREJEVTGIGS : 'venues/rejectGigs.php',
    LOOKINGFOR: 'venues/putLookingFor.php',
    VENUEFORGOTPASSWORD: 'venues/forgotPassword.php',
    VENUECHANGEEMAIL: 'venues/changeEmailAddress.php',
    VENUEBOOKGIGS: 'venues/bookGigs.php',
    VENUESENDMESSAGE: 'venues/sendMessage.php',
    VENUEEDITPROFILE: 'venues/editVenueProfile.php',
    TYPEOFVENUE: 'venues/getVenueTypes.php',


    //Chat

        CHATSENDMESSAGE: 'projects/chatSendMessage.php',
        CHATSENDMESSAGELIST: 'projects/chatSendMessageList.php',
    
};